apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: mmichelier/web:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: webapp
  labels:
    app: webserver
spec:
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 80
      targetPort: 8080
  selector:
    app: webserver
  type: NodePort
